# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '口袋名單' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 口袋名單
    pod 'SwiftLint'
    pod 'Firebase/Auth'
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'XLPagerTabStrip', '~> 7.0'
    pod 'Firebase/Storage'
	pod 'Fabric'
	pod 'Crashlytics'
end
